# Generated by Django 5.1.4 on 2026-09-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_ttl_days', models.PositiveIntegerField(default=7, help_text='Отсчитывается от момента выдачи приглашения.', verbose_name='Срок жизни приглашения ученика, дней')),
                ('share_ttl_days', models.PositiveIntegerField(default=2, help_text='Отсчитывается от конца урока, а не от создания ссылки: иначе ссылка на урок через неделю протухла бы до самого урока.', verbose_name='Срок жизни ссылки на урок, дней')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки платформы',
                'verbose_name_plural': 'Настройки платформы',
            },
        ),
    ]
