# Generated by Django 5.1.4 on 2026-09-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinvite',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Пусто — бессрочно. Проставляется при выдаче из настроек платформы.', null=True, verbose_name='Действует до'),
        ),
    ]
