# Generated by Django 5.1.4 on 2026-09-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentinvite_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_lesson_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность урока по умолчанию, мин'),
        ),
    ]
