# Generated by Django 5.1.4 on 2026-08-27 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, verbose_name='Данные доски')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Снапшот доски',
                'verbose_name_plural': 'Снапшоты досок',
                'ordering': ['-version'],
                'get_latest_by': 'version',
            },
        ),
        migrations.CreateModel(
            name='WhiteboardYjsState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField(verbose_name='Yjs state (base64)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yjs_state', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Yjs-состояние доски',
                'verbose_name_plural': 'Yjs-состояния досок',
            },
        ),
    ]
