# Generated by Django 5.1.4 on 2026-09-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhiteboardSnapshot',
        ),
    ]
