# Generated by Django 5.1.4 on 2026-08-27 14:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, verbose_name='Задание')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='homework/%Y/%m/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Тема')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (мин)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки преподавателя')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('active', 'Идёт'), ('finished', 'Завершён')], default='scheduled', max_length=20)),
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['-scheduled_at', '-created_at'],
            },
        ),
    ]
