# Generated by Django 5.1.4 on 2026-09-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_lesson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='share_expires_at',
            field=models.DateTimeField(blank=True, help_text='Пусто — считается от конца урока по настройкам платформы. Заполните, чтобы задать свой срок для этого урока.', null=True, verbose_name='Ссылка действует до'),
        ),
    ]
