# Generated by Django 5.1.4 on 2026-09-02 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_share_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отменён'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Кто отменил'),
        ),
    ]
