# Generated by Django 5.1.4 on 2026-09-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lesson_cancel_reason_lesson_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='has_whiteboard',
            field=models.BooleanField(default=True, help_text='Выключите для очного занятия: останутся заметки и домашние задания.', verbose_name='Совместная доска'),
        ),
    ]
