# Generated by Django 5.1.4 on 2026-09-03 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def split_threads(apps, schema_editor):
    """
    Разносим прежнюю общую переписку по веткам «задание + ученик».

    Сообщение ученика — его собственная ветка, тут гадать нечего. Сообщение
    преподавателя относим к ученику только если он на уроке один: у урока с
    двумя учениками адресат задним числом не определяется, и такие сообщения
    остаются общими (см. комментарий у поля).
    """
    HomeworkMessage = apps.get_model('lessons', 'HomeworkMessage')

    for message in HomeworkMessage.objects.select_related('homework__lesson', 'author'):
        if message.author_id != message.homework.lesson.teacher_id:
            message.student_id = message.author_id
        else:
            students = list(message.homework.lesson.students.values_list('id', flat=True))
            if len(students) != 1:
                continue
            message.student_id = students[0]
        message.save(update_fields=['student'])


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_homework_due_at_submissions_and_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkmessage',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework_threads', to=settings.AUTH_USER_MODEL, verbose_name='Чья ветка'),
        ),
        migrations.RunPython(split_threads, migrations.RunPython.noop),
    ]
